# Configuration file for MessageTones

# Recommended Sounds: 16, 104, 117
# default: msgSound: 104
# default: replySound: 104
msgSound: 104
replySound: 104

metrics: true

# Language
noconsole: '&cConsole cannot run MessageTones commands!'