# Configuration file for MessageTones 1.9
# https://www.spigotmc.org/resources/messagetones.30529/
# Created by KevinNovak

# ============================================
# Help
# ============================================
# Sound
#  - The ID of the sound to play.
#  - See the "Sound IDS" section for a list of IDs.
# Pitch
#  - The pitch to play the sound at.
#  - For example 1.0 is the normal sound pitch.
#  - 0.5 would create a lower pitch.
#  - 2.0 would create a higher pitch.
# Volume
#  - The volume to play the sound at.
#  - For example 1.0 is the normal sound volume.
#  - 0.5 would create a quieter sound.
#  - 2.0 would create a louder sound.

# ============================================
# Metrics
# ============================================
# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/MessageTones/
# default: metrics: true
metrics: true

# ============================================
# Private Messages
# ============================================
# Whether private messages should play sounds to players.
# default: msgEnabled: true
msgEnabled: true

# Should private messages sounds should be "On" for new players?
# default: msgDefaultOn: true
msgDefaultOn: true

# Recommended Sounds: 259 (ENTITY_ITEM_PICKUP), 72 (BLOCK_NOTE_PLING), 290 (ENTITY_PLAYER_BURP)
# default: msgSound: 259
msgSound: 259

# default: msgPitch: 1.0
msgPitch: 1.0

# default: msgVolume: 0.8
msgVolume: 0.8

# The message text that triggers a sound.
# Should uniquely identify private messages.
# For example, in Essentials/EssentialsX every message contains " -> me]".
# default: msgTrigger: ' -> me]'
msgTrigger: ' -> me]'

# ============================================
# Broadcast
# ============================================
# Whether broadcasted messages should play sounds to players.
# Broadcaster must have the messagetones.broadcast permission.
# default: broadcastEnabled: true
broadcastEnabled: true

# Should broadcast sounds be "On" for new players?
# default: msgDefaultOn: true
broadcastDefaultOn: true

# Recommended Sounds: 199 (ENTITY_FIREWORK_LARGE_BLAST), 263 (ENTITY_LIGHTNING_THUNDER)
# default: broadcastSound: 199
broadcastSound: 199

# default: broadcastPitch: 1.0
broadcastPitch: 1.0

# default: broadcastVolume: 1.0
broadcastVolume: 1.0

# The broadcast command that triggers a sound.
# default: broadcastCommand: 'broadcast'
broadcastCommand: 'broadcast'

# ============================================
# Joining
# ============================================
# The time in milliseconds to wait after a 
# player login before playing a sound.
# Useful to prevent sound glitches.
# default: delaySoundAfterJoin: 500
delaySoundAfterJoin: 500

# ============================================
# Player Joins
# ============================================
# Whether to play a sound when normal players join.
# default: joinPlayerEnabled: false
joinPlayerEnabled: true

# Should player join sounds should be "On" for new players?
# default: joinPlayerDefaultOn: true
joinPlayerDefaultOn: true

# Recommended Sounds: 111 (BLOCK_WOODEN_DOOR_OPEN)
# default: joinPlayerSound: 111
joinPlayerSound: 111

# default: joinPlayerPitch: 1.0
joinPlayerPitch: 1.0

# default: joinPlayerVolume: 0.5
joinPlayerVolume: 0.5

# ============================================
# Admin Joins
# ============================================
# Whether to play a sound when an admin joins.
# Admin must have the messagetones.admin permission.
# default: joinAdminEnabled: false
joinAdminEnabled: true

# Should admin join sounds should be "On" for new players?
# default: joinAdminDefaultOn: true
joinAdminDefaultOn: true

# Recommended Sounds: 203 (ENTITY_FIREWORK_TWINKLE)
# default: joinAdminSound: 203
joinAdminSound: 203

# default: joinAdminPitch: 1.0
joinAdminPitch: 1.0

# default: joinAdminVolume: 0.5
joinAdminVolume: 0.5

# ============================================
# Owner Joins
# ============================================
# Whether to play a sound when an owner joins.
# Owner must have the messagetones.owner permission.
# default: joinOwnerEnabled: false
joinOwnerEnabled: true

# Should owner join sounds should be "On" for new players?
# default: joinOwnerDefaultOn: true
joinOwnerDefaultOn: true

# Recommended Sounds: 293 (ENTITY_PLAYER_LEVELUP)
# default: joinOwnerSound: 293
joinOwnerSound: 293

# default: joinOwnerPitch: 1.0
joinOwnerPitch: 1.0

# default: joinOwnerVolume: 0.5
joinOwnerVolume: 0.5

# ============================================
# Hotbar
# ============================================
# Whether to play a sound when players switch items in the hotbar.
# default: hotbarEnabled: false
hotbarEnabled: false

# Should hotbar sounds should be "On" for new players?
# default: hotbarDefaultOn: true
hotbarDefaultOn: true

# Recommended Sounds: 259 (ENTITY_ITEM_PICKUP)
# default: hotbarSound: 259
hotbarSound: 259

# default: hotbarPitch: 0.5
hotbarPitch: 0.5

# default: hotbarVolume: 0.2
hotbarVolume: 0.2

# ============================================
# Help Language
# ============================================
helpHeader: '&e---------- &6MessageTones &e- &6Help &e----------'
helpFooter: '&e---------------------------------------'
helpMessage: '&b{COMMAND} &7- {INFO}.'
helpPage: '&7Type &6/mt {PAGE} &7for more info.'
helpNoCommands: '&7You are not allowed to use commands.'

infoStatus: 'shows your preferences'
infoTestSound: 'plays a test {SOUND} sound'
infoToggleSound: 'toggles {SOUND} sound'

# ============================================
# Status Language
# ============================================
statusHeader: '&e--------- &6MessageTones &e- &6Status &e---------'
statusFooter: '&e---------------------------------------'
statusMessage: '&b{SOUND} &7- {STATUS}'

toggleMessage: '&b{SOUND} &7is now {STATUS}&7!'

nameMessage: 'Message'
nameBroadcast: 'Broadcast'
namePlayerJoin: 'Player Join'
nameAdminJoin: 'Admin Join'
nameOwnerJoin: 'Owner Join'
nameHotbar: 'Hotbar'

statusOn: '&aOn'
statusOff: '&cOff'

# ============================================
# Misc Language
# ============================================
testMessage: '&7Played a test {SOUND} sound.'

noConsole: '&cConsole cannot run MessageTones commands!'
notPermitted: '&cYou are not permitted to do this!'

# ============================================
# Minecraft 1.9 - Sound IDs
# ============================================
# 1 - AMBIENT_CAVE
# 2 - BLOCK_ANVIL_BREAK
# 3 - BLOCK_ANVIL_DESTROY
# 4 - BLOCK_ANVIL_FALL
# 5 - BLOCK_ANVIL_HIT
# 6 - BLOCK_ANVIL_LAND
# 7 - BLOCK_ANVIL_PLACE
# 8 - BLOCK_ANVIL_STEP
# 9 - BLOCK_ANVIL_USE
# 10 - BLOCK_BREWING_STAND_BREW
# 11 - BLOCK_CHEST_CLOSE
# 12 - BLOCK_CHEST_LOCKED
# 13 - BLOCK_CHEST_OPEN
# 14 - BLOCK_CHORUS_FLOWER_DEATH
# 15 - BLOCK_CHORUS_FLOWER_GROW
# 16 - BLOCK_CLOTH_BREAK
# 17 - BLOCK_CLOTH_FALL
# 18 - BLOCK_CLOTH_HIT
# 19 - BLOCK_CLOTH_PLACE
# 20 - BLOCK_CLOTH_STEP
# 21 - BLOCK_COMPARATOR_CLICK
# 22 - BLOCK_DISPENSER_DISPENSE
# 23 - BLOCK_DISPENSER_FAIL
# 24 - BLOCK_DISPENSER_LAUNCH
# 25 - BLOCK_ENDERCHEST_CLOSE
# 26 - BLOCK_ENDERCHEST_OPEN
# 27 - BLOCK_END_GATEWAY_SPAWN
# 28 - BLOCK_FENCE_GATE_CLOSE
# 29 - BLOCK_FENCE_GATE_OPEN
# 30 - BLOCK_FIRE_AMBIENT
# 31 - BLOCK_FIRE_EXTINGUISH
# 32 - BLOCK_FURNACE_FIRE_CRACKLE
# 33 - BLOCK_GLASS_BREAK
# 34 - BLOCK_GLASS_FALL
# 35 - BLOCK_GLASS_HIT
# 36 - BLOCK_GLASS_PLACE
# 37 - BLOCK_GLASS_STEP
# 38 - BLOCK_GRASS_BREAK
# 39 - BLOCK_GRASS_FALL
# 40 - BLOCK_GRASS_HIT
# 41 - BLOCK_GRASS_PLACE
# 42 - BLOCK_GRASS_STEP
# 43 - BLOCK_GRAVEL_BREAK
# 44 - BLOCK_GRAVEL_FALL
# 45 - BLOCK_GRAVEL_HIT
# 46 - BLOCK_GRAVEL_PLACE
# 47 - BLOCK_GRAVEL_STEP
# 48 - BLOCK_IRON_DOOR_CLOSE
# 49 - BLOCK_IRON_DOOR_OPEN
# 50 - BLOCK_IRON_TRAPDOOR_CLOSE
# 51 - BLOCK_IRON_TRAPDOOR_OPEN
# 52 - BLOCK_LADDER_BREAK
# 53 - BLOCK_LADDER_FALL
# 54 - BLOCK_LADDER_HIT
# 55 - BLOCK_LADDER_PLACE
# 56 - BLOCK_LADDER_STEP
# 57 - BLOCK_LAVA_AMBIENT
# 58 - BLOCK_LAVA_EXTINGUISH
# 59 - BLOCK_LAVA_POP
# 60 - BLOCK_LEVER_CLICK
# 61 - BLOCK_METAL_BREAK
# 62 - BLOCK_METAL_FALL
# 63 - BLOCK_METAL_HIT
# 64 - BLOCK_METAL_PLACE
# 65 - BLOCK_METAL_PRESSUREPLATE_CLICK_OFF
# 66 - BLOCK_METAL_PRESSUREPLATE_CLICK_ON
# 67 - BLOCK_METAL_STEP
# 68 - BLOCK_NOTE_BASEDRUM
# 69 - BLOCK_NOTE_BASS
# 70 - BLOCK_NOTE_HARP
# 71 - BLOCK_NOTE_HAT
# 72 - BLOCK_NOTE_PLING
# 73 - BLOCK_NOTE_SNARE
# 74 - BLOCK_PISTON_CONTRACT
# 75 - BLOCK_PISTON_EXTEND
# 76 - BLOCK_PORTAL_AMBIENT
# 77 - BLOCK_PORTAL_TRAVEL
# 78 - BLOCK_PORTAL_TRIGGER
# 79 - BLOCK_REDSTONE_TORCH_BURNOUT
# 80 - BLOCK_SAND_BREAK
# 81 - BLOCK_SAND_FALL
# 82 - BLOCK_SAND_HIT
# 83 - BLOCK_SAND_PLACE
# 84 - BLOCK_SAND_STEP
# 85 - BLOCK_SLIME_BREAK
# 86 - BLOCK_SLIME_FALL
# 87 - BLOCK_SLIME_HIT
# 88 - BLOCK_SLIME_PLACE
# 89 - BLOCK_SLIME_STEP
# 90 - BLOCK_SNOW_BREAK
# 91 - BLOCK_SNOW_FALL
# 92 - BLOCK_SNOW_HIT
# 93 - BLOCK_SNOW_PLACE
# 94 - BLOCK_SNOW_STEP
# 95 - BLOCK_STONE_BREAK
# 96 - BLOCK_STONE_BUTTON_CLICK_OFF
# 97 - BLOCK_STONE_BUTTON_CLICK_ON
# 98 - BLOCK_STONE_FALL
# 99 - BLOCK_STONE_HIT
# 100 - BLOCK_STONE_PLACE
# 101 - BLOCK_STONE_PRESSUREPLATE_CLICK_OFF
# 102 - BLOCK_STONE_PRESSUREPLATE_CLICK_ON
# 103 - BLOCK_STONE_STEP
# 104 - BLOCK_TRIPWIRE_ATTACH
# 105 - BLOCK_TRIPWIRE_CLICK_OFF
# 106 - BLOCK_TRIPWIRE_CLICK_ON
# 107 - BLOCK_TRIPWIRE_DETACH
# 108 - BLOCK_WATERLILY_PLACE
# 109 - BLOCK_WATER_AMBIENT
# 110 - BLOCK_WOODEN_DOOR_CLOSE
# 111 - BLOCK_WOODEN_DOOR_OPEN
# 112 - BLOCK_WOODEN_TRAPDOOR_CLOSE
# 113 - BLOCK_WOODEN_TRAPDOOR_OPEN
# 114 - BLOCK_WOOD_BREAK
# 115 - BLOCK_WOOD_BUTTON_CLICK_OFF
# 116 - BLOCK_WOOD_BUTTON_CLICK_ON
# 117 - BLOCK_WOOD_FALL
# 118 - BLOCK_WOOD_HIT
# 119 - BLOCK_WOOD_PLACE
# 120 - BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF
# 121 - BLOCK_WOOD_PRESSUREPLATE_CLICK_ON
# 122 - BLOCK_WOOD_STEP
# 123 - ENCHANT_THORNS_HIT
# 124 - ENTITY_ARMORSTAND_BREAK
# 125 - ENTITY_ARMORSTAND_FALL
# 126 - ENTITY_ARMORSTAND_HIT
# 127 - ENTITY_ARMORSTAND_PLACE
# 128 - ENTITY_ARROW_HIT
# 129 - ENTITY_ARROW_HIT_PLAYER
# 130 - ENTITY_ARROW_SHOOT
# 131 - ENTITY_BAT_AMBIENT
# 132 - ENTITY_BAT_DEATH
# 133 - ENTITY_BAT_HURT
# 134 - ENTITY_BAT_LOOP
# 135 - ENTITY_BAT_TAKEOFF
# 136 - ENTITY_BLAZE_AMBIENT
# 137 - ENTITY_BLAZE_BURN
# 138 - ENTITY_BLAZE_DEATH
# 139 - ENTITY_BLAZE_HURT
# 140 - ENTITY_BLAZE_SHOOT
# 141 - ENTITY_BOBBER_SPLASH
# 142 - ENTITY_BOBBER_THROW
# 143 - ENTITY_CAT_AMBIENT
# 144 - ENTITY_CAT_DEATH
# 145 - ENTITY_CAT_HISS
# 146 - ENTITY_CAT_HURT
# 147 - ENTITY_CAT_PURR
# 148 - ENTITY_CAT_PURREOW
# 149 - ENTITY_CHICKEN_AMBIENT
# 150 - ENTITY_CHICKEN_DEATH
# 151 - ENTITY_CHICKEN_EGG
# 152 - ENTITY_CHICKEN_HURT
# 153 - ENTITY_CHICKEN_STEP
# 154 - ENTITY_COW_AMBIENT
# 155 - ENTITY_COW_DEATH
# 156 - ENTITY_COW_HURT
# 157 - ENTITY_COW_MILK
# 158 - ENTITY_COW_STEP
# 159 - ENTITY_CREEPER_DEATH
# 160 - ENTITY_CREEPER_HURT
# 161 - ENTITY_CREEPER_PRIMED
# 162 - ENTITY_DONKEY_AMBIENT
# 163 - ENTITY_DONKEY_ANGRY
# 164 - ENTITY_DONKEY_CHEST
# 165 - ENTITY_DONKEY_DEATH
# 166 - ENTITY_DONKEY_HURT
# 167 - ENTITY_EGG_THROW
# 168 - ENTITY_ELDER_GUARDIAN_AMBIENT
# 169 - ENTITY_ELDER_GUARDIAN_AMBIENT_LAND
# 170 - ENTITY_ELDER_GUARDIAN_CURSE
# 171 - ENTITY_ELDER_GUARDIAN_DEATH
# 172 - ENTITY_ELDER_GUARDIAN_DEATH_LAND
# 173 - ENTITY_ELDER_GUARDIAN_HURT
# 174 - ENTITY_ELDER_GUARDIAN_HURT_LAND
# 175 - ENTITY_ENDERDRAGON_AMBIENT
# 176 - ENTITY_ENDERDRAGON_DEATH
# 177 - ENTITY_ENDERDRAGON_FIREBALL_EXPLODE
# 178 - ENTITY_ENDERDRAGON_FLAP
# 179 - ENTITY_ENDERDRAGON_GROWL
# 180 - ENTITY_ENDERDRAGON_HURT
# 181 - ENTITY_ENDERDRAGON_SHOOT
# 182 - ENTITY_ENDEREYE_LAUNCH
# 183 - ENTITY_ENDERMEN_AMBIENT
# 184 - ENTITY_ENDERMEN_DEATH
# 185 - ENTITY_ENDERMEN_HURT
# 186 - ENTITY_ENDERMEN_SCREAM
# 187 - ENTITY_ENDERMEN_STARE
# 188 - ENTITY_ENDERMEN_TELEPORT
# 189 - ENTITY_ENDERMITE_AMBIENT
# 190 - ENTITY_ENDERMITE_DEATH
# 191 - ENTITY_ENDERMITE_HURT
# 192 - ENTITY_ENDERMITE_STEP
# 193 - ENTITY_ENDERPEARL_THROW
# 194 - ENTITY_EXPERIENCE_BOTTLE_THROW
# 195 - ENTITY_EXPERIENCE_ORB_PICKUP
# 196 - ENTITY_EXPERIENCE_ORB_TOUCH
# 197 - ENTITY_FIREWORK_BLAST
# 198 - ENTITY_FIREWORK_BLAST_FAR
# 199 - ENTITY_FIREWORK_LARGE_BLAST
# 200 - ENTITY_FIREWORK_LARGE_BLAST_FAR
# 201 - ENTITY_FIREWORK_LAUNCH
# 202 - ENTITY_FIREWORK_SHOOT
# 203 - ENTITY_FIREWORK_TWINKLE
# 204 - ENTITY_FIREWORK_TWINKLE_FAR
# 205 - ENTITY_GENERIC_BIG_FALL
# 206 - ENTITY_GENERIC_BURN
# 207 - ENTITY_GENERIC_DEATH
# 208 - ENTITY_GENERIC_DRINK
# 209 - ENTITY_GENERIC_EAT
# 210 - ENTITY_GENERIC_EXPLODE
# 211 - ENTITY_GENERIC_EXTINGUISH_FIRE
# 212 - ENTITY_GENERIC_HURT
# 213 - ENTITY_GENERIC_SMALL_FALL
# 214 - ENTITY_GENERIC_SPLASH
# 215 - ENTITY_GENERIC_SWIM
# 216 - ENTITY_GHAST_AMBIENT
# 217 - ENTITY_GHAST_DEATH
# 218 - ENTITY_GHAST_HURT
# 219 - ENTITY_GHAST_SCREAM
# 220 - ENTITY_GHAST_SHOOT
# 221 - ENTITY_GHAST_WARN
# 222 - ENTITY_GUARDIAN_AMBIENT
# 223 - ENTITY_GUARDIAN_AMBIENT_LAND
# 224 - ENTITY_GUARDIAN_ATTACK
# 225 - ENTITY_GUARDIAN_DEATH
# 226 - ENTITY_GUARDIAN_DEATH_LAND
# 227 - ENTITY_GUARDIAN_FLOP
# 228 - ENTITY_GUARDIAN_HURT
# 229 - ENTITY_GUARDIAN_HURT_LAND
# 230 - ENTITY_HORSE_AMBIENT
# 231 - ENTITY_HORSE_ANGRY
# 232 - ENTITY_HORSE_ARMOR
# 233 - ENTITY_HORSE_BREATHE
# 234 - ENTITY_HORSE_DEATH
# 235 - ENTITY_HORSE_EAT
# 236 - ENTITY_HORSE_GALLOP
# 237 - ENTITY_HORSE_HURT
# 238 - ENTITY_HORSE_JUMP
# 239 - ENTITY_HORSE_LAND
# 240 - ENTITY_HORSE_SADDLE
# 241 - ENTITY_HORSE_STEP
# 242 - ENTITY_HORSE_STEP_WOOD
# 243 - ENTITY_HOSTILE_BIG_FALL
# 244 - ENTITY_HOSTILE_DEATH
# 245 - ENTITY_HOSTILE_HURT
# 246 - ENTITY_HOSTILE_SMALL_FALL
# 247 - ENTITY_HOSTILE_SPLASH
# 248 - ENTITY_HOSTILE_SWIM
# 249 - ENTITY_IRONGOLEM_ATTACK
# 250 - ENTITY_IRONGOLEM_DEATH
# 251 - ENTITY_IRONGOLEM_HURT
# 252 - ENTITY_IRONGOLEM_STEP
# 253 - ENTITY_ITEMFRAME_ADD_ITEM
# 254 - ENTITY_ITEMFRAME_BREAK
# 255 - ENTITY_ITEMFRAME_PLACE
# 256 - ENTITY_ITEMFRAME_REMOVE_ITEM
# 257 - ENTITY_ITEMFRAME_ROTATE_ITEM
# 258 - ENTITY_ITEM_BREAK
# 259 - ENTITY_ITEM_PICKUP
# 260 - ENTITY_LEASHKNOT_BREAK
# 261 - ENTITY_LEASHKNOT_PLACE
# 262 - ENTITY_LIGHTNING_IMPACT
# 263 - ENTITY_LIGHTNING_THUNDER
# 264 - ENTITY_LINGERINGPOTION_THROW
# 265 - ENTITY_MAGMACUBE_DEATH
# 266 - ENTITY_MAGMACUBE_HURT
# 267 - ENTITY_MAGMACUBE_JUMP
# 268 - ENTITY_MAGMACUBE_SQUISH
# 269 - ENTITY_MINECART_INSIDE
# 270 - ENTITY_MINECART_RIDING
# 271 - ENTITY_MOOSHROOM_SHEAR
# 272 - ENTITY_MULE_AMBIENT
# 273 - ENTITY_MULE_DEATH
# 274 - ENTITY_MULE_HURT
# 275 - ENTITY_PAINTING_BREAK
# 276 - ENTITY_PAINTING_PLACE
# 277 - ENTITY_PIG_AMBIENT
# 278 - ENTITY_PIG_DEATH
# 279 - ENTITY_PIG_HURT
# 280 - ENTITY_PIG_SADDLE
# 281 - ENTITY_PIG_STEP
# 282 - ENTITY_PLAYER_ATTACK_CRIT
# 283 - ENTITY_PLAYER_ATTACK_KNOCKBACK
# 284 - ENTITY_PLAYER_ATTACK_NODAMAGE
# 285 - ENTITY_PLAYER_ATTACK_STRONG
# 286 - ENTITY_PLAYER_ATTACK_SWEEP
# 287 - ENTITY_PLAYER_ATTACK_WEAK
# 288 - ENTITY_PLAYER_BIG_FALL
# 289 - ENTITY_PLAYER_BREATH
# 290 - ENTITY_PLAYER_BURP
# 291 - ENTITY_PLAYER_DEATH
# 292 - ENTITY_PLAYER_HURT
# 293 - ENTITY_PLAYER_LEVELUP
# 294 - ENTITY_PLAYER_SMALL_FALL
# 295 - ENTITY_PLAYER_SPLASH
# 296 - ENTITY_PLAYER_SWIM
# 297 - ENTITY_RABBIT_AMBIENT
# 298 - ENTITY_RABBIT_ATTACK
# 299 - ENTITY_RABBIT_DEATH
# 300 - ENTITY_RABBIT_HURT
# 301 - ENTITY_RABBIT_JUMP
# 302 - ENTITY_SHEEP_AMBIENT
# 303 - ENTITY_SHEEP_DEATH
# 304 - ENTITY_SHEEP_HURT
# 305 - ENTITY_SHEEP_SHEAR
# 306 - ENTITY_SHEEP_STEP
# 307 - ENTITY_SHULKER_AMBIENT
# 308 - ENTITY_SHULKER_BULLET_HIT
# 309 - ENTITY_SHULKER_BULLET_HURT
# 310 - ENTITY_SHULKER_CLOSE
# 311 - ENTITY_SHULKER_DEATH
# 312 - ENTITY_SHULKER_HURT
# 313 - ENTITY_SHULKER_HURT_CLOSED
# 314 - ENTITY_SHULKER_OPEN
# 315 - ENTITY_SHULKER_SHOOT
# 316 - ENTITY_SHULKER_TELEPORT
# 317 - ENTITY_SILVERFISH_AMBIENT
# 318 - ENTITY_SILVERFISH_DEATH
# 319 - ENTITY_SILVERFISH_HURT
# 320 - ENTITY_SILVERFISH_STEP
# 321 - ENTITY_SKELETON_AMBIENT
# 322 - ENTITY_SKELETON_DEATH
# 323 - ENTITY_SKELETON_HORSE_AMBIENT
# 324 - ENTITY_SKELETON_HORSE_DEATH
# 325 - ENTITY_SKELETON_HORSE_HURT
# 326 - ENTITY_SKELETON_HURT
# 327 - ENTITY_SKELETON_SHOOT
# 328 - ENTITY_SKELETON_STEP
# 329 - ENTITY_SLIME_ATTACK
# 330 - ENTITY_SLIME_DEATH
# 331 - ENTITY_SLIME_HURT
# 332 - ENTITY_SLIME_JUMP
# 333 - ENTITY_SLIME_SQUISH
# 334 - ENTITY_SMALL_MAGMACUBE_DEATH
# 335 - ENTITY_SMALL_MAGMACUBE_HURT
# 336 - ENTITY_SMALL_MAGMACUBE_SQUISH
# 337 - ENTITY_SMALL_SLIME_DEATH
# 338 - ENTITY_SMALL_SLIME_HURT
# 339 - ENTITY_SMALL_SLIME_JUMP
# 340 - ENTITY_SMALL_SLIME_SQUISH
# 341 - ENTITY_SNOWBALL_THROW
# 342 - ENTITY_SNOWMAN_AMBIENT
# 343 - ENTITY_SNOWMAN_DEATH
# 344 - ENTITY_SNOWMAN_HURT
# 345 - ENTITY_SNOWMAN_SHOOT
# 346 - ENTITY_SPIDER_AMBIENT
# 347 - ENTITY_SPIDER_DEATH
# 348 - ENTITY_SPIDER_HURT
# 349 - ENTITY_SPIDER_STEP
# 350 - ENTITY_SPLASH_POTION_BREAK
# 351 - ENTITY_SPLASH_POTION_THROW
# 352 - ENTITY_SQUID_AMBIENT
# 353 - ENTITY_SQUID_DEATH
# 354 - ENTITY_SQUID_HURT
# 355 - ENTITY_TNT_PRIMED
# 356 - ENTITY_VILLAGER_AMBIENT
# 357 - ENTITY_VILLAGER_DEATH
# 358 - ENTITY_VILLAGER_HURT
# 359 - ENTITY_VILLAGER_NO
# 360 - ENTITY_VILLAGER_TRADING
# 361 - ENTITY_VILLAGER_YES
# 362 - ENTITY_WITCH_AMBIENT
# 363 - ENTITY_WITCH_DEATH
# 364 - ENTITY_WITCH_DRINK
# 365 - ENTITY_WITCH_HURT
# 366 - ENTITY_WITCH_THROW
# 367 - ENTITY_WITHER_AMBIENT
# 368 - ENTITY_WITHER_BREAK_BLOCK
# 369 - ENTITY_WITHER_DEATH
# 370 - ENTITY_WITHER_HURT
# 371 - ENTITY_WITHER_SHOOT
# 372 - ENTITY_WITHER_SPAWN
# 373 - ENTITY_WOLF_AMBIENT
# 374 - ENTITY_WOLF_DEATH
# 375 - ENTITY_WOLF_GROWL
# 376 - ENTITY_WOLF_HOWL
# 377 - ENTITY_WOLF_HURT
# 378 - ENTITY_WOLF_PANT
# 379 - ENTITY_WOLF_SHAKE
# 380 - ENTITY_WOLF_STEP
# 381 - ENTITY_WOLF_WHINE
# 382 - ENTITY_ZOMBIE_AMBIENT
# 383 - ENTITY_ZOMBIE_ATTACK_DOOR_WOOD
# 384 - ENTITY_ZOMBIE_ATTACK_IRON_DOOR
# 385 - ENTITY_ZOMBIE_BREAK_DOOR_WOOD
# 386 - ENTITY_ZOMBIE_DEATH
# 387 - ENTITY_ZOMBIE_HORSE_AMBIENT
# 388 - ENTITY_ZOMBIE_HORSE_DEATH
# 389 - ENTITY_ZOMBIE_HORSE_HURT
# 390 - ENTITY_ZOMBIE_HURT
# 391 - ENTITY_ZOMBIE_INFECT
# 392 - ENTITY_ZOMBIE_PIG_AMBIENT
# 393 - ENTITY_ZOMBIE_PIG_ANGRY
# 394 - ENTITY_ZOMBIE_PIG_DEATH
# 395 - ENTITY_ZOMBIE_PIG_HURT
# 396 - ENTITY_ZOMBIE_STEP
# 397 - ENTITY_ZOMBIE_VILLAGER_AMBIENT
# 398 - ENTITY_ZOMBIE_VILLAGER_CONVERTED
# 399 - ENTITY_ZOMBIE_VILLAGER_CURE
# 400 - ENTITY_ZOMBIE_VILLAGER_DEATH
# 401 - ENTITY_ZOMBIE_VILLAGER_HURT
# 402 - ENTITY_ZOMBIE_VILLAGER_STEP
# 403 - ITEM_ARMOR_EQUIP_CHAIN
# 404 - ITEM_ARMOR_EQUIP_DIAMOND
# 405 - ITEM_ARMOR_EQUIP_GENERIC
# 406 - ITEM_ARMOR_EQUIP_GOLD
# 407 - ITEM_ARMOR_EQUIP_IRON
# 408 - ITEM_ARMOR_EQUIP_LEATHER
# 409 - ITEM_BOTTLE_FILL
# 410 - ITEM_BOTTLE_FILL_DRAGONBREATH
# 411 - ITEM_BUCKET_EMPTY
# 412 - ITEM_BUCKET_EMPTY_LAVA
# 413 - ITEM_BUCKET_FILL
# 414 - ITEM_BUCKET_FILL_LAVA
# 415 - ITEM_CHORUS_FRUIT_TELEPORT
# 416 - ITEM_ELYTRA_FLYING
# 417 - ITEM_FIRECHARGE_USE
# 418 - ITEM_FLINTANDSTEEL_USE
# 419 - ITEM_HOE_TILL
# 420 - ITEM_SHIELD_BLOCK
# 421 - ITEM_SHIELD_BREAK
# 422 - ITEM_SHOVEL_FLATTEN
# 423 - MUSIC_CREATIVE
# 424 - MUSIC_CREDITS
# 425 - MUSIC_DRAGON
# 426 - MUSIC_END
# 427 - MUSIC_GAME
# 428 - MUSIC_MENU
# 429 - MUSIC_NETHER
# 430 - RECORD_11
# 431 - RECORD_13
# 432 - RECORD_BLOCKS
# 433 - RECORD_CAT
# 434 - RECORD_CHIRP
# 435 - RECORD_FAR
# 436 - RECORD_MALL
# 437 - RECORD_MELLOHI
# 438 - RECORD_STAL
# 439 - RECORD_STRAD
# 440 - RECORD_WAIT
# 441 - RECORD_WARD
# 442 - UI_BUTTON_CLICK
# 443 - WEATHER_RAIN
# 444 - WEATHER_RAIN_ABOVE

# Do not touch:
copied: true
