name: MessageTones
version: 1.1.3
main: me.kevinnovak.messagetones.MessageTones
author: KevinNovak
description: Add sounds to private messages, broadcasts, player joins, and more!
depend: [ProtocolLib]

commands:
    mt:
        usage: /<command>
        description: Lists MessageTones commands.
        aliases: [messagetones]
        
permissions:
    messagetones.broadcast:
        description: Plays sound on /broadcast.
        default: op
    messagetones.admin:
        description: Plays admin login sound.
        default: false
    messagetones.owner:
        description: Plays owner login sound.
        default: false