name: MessageTones
version: 1.2.2
main: me.kevinnovak.messagetones.MessageTones
author: KevinNovak
description: Allows messages to have tones!
depend: [ProtocolLib]

commands:
    mt:
        usage: /<command>
        description: Plays a test sound.
        
permissions:
    messagetones.broadcast:
        description: Plays sound on /broadcast.
        default: op
    messagetones.admin:
        description: Plays admin login sound.
        default: false