# Temporary Configuration file for MessageTones
# Created by KevinNovak

# If you are seeing this, please fill in a bug report at:
# https://goo.gl/forms/VVYMCzaqSvq5OF3V2

# Do not touch:
copied: false