# Configuration file for MessageTones

# ============================================
# Help
# ============================================
# Sound
#  - The ID of the sound to play.
#  - See the "Sound IDS" section for a list of IDs.
# Pitch
#  - The pitch to play the sound at.
#  - For example 1.0 is the normal sound pitch.
#  - 0.5 would create a lower pitch.
#  - 2.0 would create a higher pitch.
# Volume
#  - The volume to play the sound at.
#  - For example 1.0 is the normal sound volume.
#  - 0.5 would create a quieter sound.
#  - 2.0 would create a louder sound.

# ============================================
# Private Messages
# ============================================
# Whether private messages should play sounds to players.
# default: msgEnabled: true
msgEnabled: true

# Recommended Sounds: 16 (Burp), 104 (ITEM_PICKUP), 117 (NOTE_PLING)
# default: msgSound: 104
msgSound: 104

# default: msgPitch: 1.0
msgPitch: 1.0

# default: msgVolume: 0.8
msgVolume: 0.8

# The message text that triggers a sound.
# Should uniquely identify private messages.
# For example, in essentials every message contains "-> me".
# default: msgTrigger: '-> me'
msgTrigger: '-> me'

# ============================================
# Broadcast
# ============================================
# Whether broadcasted messages should play sounds to players.
# Broadcaster must have the messagetones.broadcast permission.
# default: broadcastEnabled: true
broadcastEnabled: true

# Recommended Sounds: 3 (AMBIENCE_THUNDER), 66 (FIREWORK_LARGE_BLAST)
# default: broadcastSound: 66
broadcastSound: 66

# default: broadcastPitch: 1.0
broadcastPitch: 1.0

# default: broadcastVolume: 1.0
broadcastVolume: 1.0

# The broadcast command that triggers a sound.
# default: broadcastCommand: 'broadcast'
broadcastCommand: 'broadcast'

# ============================================
# Player Joins
# ============================================
# Whether to play a sound when normal players join.
# default: joinPlayerEnabled: false
joinPlayerEnabled: false

# Recommended Sounds: 46 (DOOR_OPEN)
# default: joinPlayerSound: 46
joinPlayerSound: 46

# default: joinPlayerPitch: 1.0
joinPlayerPitch: 1.0

# default: joinPlayerVolume: 0.5
joinPlayerVolume: 0.5

# ============================================
# Admin Joins
# ============================================
# Whether to play a sound when an admin joins.
# Admin must have the messagetones.admin permission.
# default: joinAdminEnabled: false
joinAdminEnabled: false

# Recommended Sounds: 69 (FIREWORK_TWINKLE)
# default: joinAdminSound: 69
joinAdminSound: 69

# default: joinAdminPitch: 1.0
joinAdminPitch: 1.0

# default: joinAdminVolume: 0.5
joinAdminVolume: 0.5

# ============================================
# Owner Joins
# ============================================
# Whether to play a sound when an owner joins.
# Owner must have the messagetones.owner permission.
# default: joinOwnerEnabled: false
joinOwnerEnabled: false

# Recommended Sounds: 107 (LEVEL_UP)
# default: joinOwnerSound: 107
joinOwnerSound: 107

# default: joinOwnerPitch: 1.0
joinOwnerPitch: 1.0

# default: joinOwnerVolume: 0.5
joinOwnerVolume: 0.5

# ============================================
# Hotbar
# ============================================
# Whether to play a sound when players switch items in the hotbar.
# default: hotbarEnabled: false
hotbarEnabled: false

# Recommended Sounds: 104 (ITEM_PICKUP)
# default: hotbarSound: 104
hotbarSound: 104

# default: hotbarPitch: 0.5
hotbarPitch: 0.5

# default: hotbarVolume: 0.2
hotbarVolume: 0.2

# ============================================
# Language
# ============================================
noconsole: '&cConsole cannot run MessageTones commands!'
noargs: '&cPlease type a sound to test!'
testmessage: '&7Played test message sound.'
testbroadcast: '&7Played test broadcast sound.'
testownerjoin: '&7Played test owner join sound.'
testadminjoin: '&7Played test admin join sound.'
testplayerjoin: '&7Played test player join sound.'
help:
- '&e---------- &6MessageTones &e----------'
- '&b/mt message &7- Test message sound.'
- '&b/mt broadcast &7- Test broadcast sound.'
- '&b/mt ownerjoin &7- Test owner join sound.'
- '&b/mt adminjoin &7- Test admin join sound.'
- '&b/mt playerjoin &7- Test player join sound.'
- '&b/mt hotbar &7- Test hotbar sound.'

# ============================================
# Metrics
# ============================================
# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/MessageTones
# default: metrics: true
metrics: true

# ============================================
# Sound IDs
# ============================================
# 1 - AMBIENCE_CAVE
# 2 - AMBIENCE_RAIN
# 3 - AMBIENCE_THUNDER
# 4 - ANVIL_BREAK
# 5 - ANVIL_LAND
# 6 - ANVIL_USE
# 7 - ARROW_HIT
# 8 - BAT_DEATH
# 9 - BAT_HURT
# 10 - BAT_IDLE
# 11 - BAT_LOOP
# 12 - BAT_TAKEOFF
# 13 - BLAZE_BREATH
# 14 - BLAZE_DEATH
# 15 - BLAZE_HIT
# 16 - BURP
# 17 - CAT_HISS
# 18 - CAT_HIT
# 19 - CAT_MEOW
# 20 - CAT_PURR
# 21 - CAT_PURREOW
# 22 - CHEST_CLOSE
# 23 - CHEST_OPEN
# 24 - CHICKEN_EGG_POP
# 25 - CHICKEN_HURT
# 26 - CHICKEN_IDLE
# 27 - CHICKEN_WALK
# 28 - CLICK
# 29 - COW_HURT
# 30 - COW_IDLE
# 31 - COW_WALK
# 32 - CREEPER_DEATH
# 33 - CREEPER_HISS
# 34 - DIG_GRASS
# 35 - DIG_GRAVEL
# 36 - DIG_SAND
# 37 - DIG_SNOW
# 38 - DIG_STONE
# 39 - DIG_WOOD
# 40 - DIG_WOOL
# 41 - DONKEY_ANGRY
# 42 - DONKEY_DEATH
# 43 - DONKEY_HIT
# 44 - DONKEY_IDLE
# 45 - DOOR_CLOSE
# 46 - DOOR_OPEN
# 47 - DRINK
# 48 - EAT
# 49 - ENDERDRAGON_DEATH
# 50 - ENDERDRAGON_GROWL
# 51 - ENDERDRAGON_HIT
# 52 - ENDERDRAGON_WINGS
# 53 - ENDERMAN_DEATH
# 54 - ENDERMAN_HIT
# 55 - ENDERMAN_IDLE
# 56 - ENDERMAN_SCREAM
# 57 - ENDERMAN_STARE
# 58 - ENDERMAN_TELEPORT
# 59 - EXPLODE
# 60 - FALL_BIG
# 61 - FALL_SMALL
# 62 - FIRE
# 63 - FIRE_IGNITE
# 64 - FIREWORK_BLAST
# 65 - FIREWORK_BLAST2
# 66 - FIREWORK_LARGE_BLAST
# 67 - FIREWORK_LARGE_BLAST2
# 68 - FIREWORK_LAUNCH
# 69 - FIREWORK_TWINKLE
# 70 - FIREWORK_TWINKLE2
# 71 - FIZZ
# 72 - FUSE
# 73 - GHAST_CHARGE
# 74 - GHAST_DEATH
# 75 - GHAST_FIREBALL
# 76 - GHAST_MOAN
# 77 - GHAST_SCREAM
# 78 - GHAST_SCREAM2
# 79 - GLASS
# 80 - HORSE_ANGRY
# 81 - HORSE_ANGRY
# 82 - HORSE_BREATHE
# 83 - HORSE_DEATH
# 84 - HORSE_GALLOP
# 85 - HORSE_HIT
# 86 - HORSE_IDLE
# 87 - HORSE_JUMP
# 88 - HORSE_LAND
# 89 - HORSE_SADDLE
# 90 - HORSE_SKELETON_DEATH
# 91 - HORSE_SKELETON_HIT
# 92 - HORSE_SKELETON_IDLE
# 93 - HORSE_SOFT
# 94 - HORSE_WOOD
# 95 - HORSE_ZOMBIE_DEATH
# 96 - HORSE_ZOMBIE_HIT
# 97 - HORSE_ZOMBIE_IDLE
# 98 - HURT_FLESH
# 99 - IRONGOLEM_DEATH
# 100 - IRONGOLEM_HIT
# 101 - IRONGOLEM_THROW
# 102 - IRONGOLEM_WALK
# 103 - ITEM_BREAK
# 104 - ITEM_PICKUP
# 105 - LAVA
# 106 - LAVA_POP
# 107 - LEVEL_UP
# 108 - MAGMACUBE_JUMP
# 109 - MAGMACUBE_WALK
# 110 - MAGMACUBE_WALK2
# 111 - MINECART_BASE
# 112 - MINECART_INSIDE
# 113 - NOTE_BASS
# 114 - NOTE_BASS_DRUM
# 115 - NOTE_BASS_GUITAR
# 116 - NOTE_PIANO
# 117 - NOTE_PLING
# 118 - NOTE_SNARE_DRUM
# 119 - NOTE_STICKS
# 120 - ORB_PICKUP
# 121 - PIG_DEATH
# 122 - PIG_IDLE
# 123 - PIG_WALK
# 124 - PISTON_EXTEND
# 125 - PISTON_RETRACT
# 126 - PISTON_RETRACT
# 127 - PORTAL
# 128 - PORTAL_TRAVEL
# 129 - PORTAL_TRIGGER
# 130 - SHEEP_IDLE
# 131 - SHEEP_SHEAR
# 132 - SHEEP_WALK
# 133 - SHOOT_ARROW
# 134 - SILVERFISH_HIT
# 135 - SILVERFISH_IDLE
# 136 - SILVERFISH_KILL
# 137 - SILVERFISH_WALK
# 138 - SKELETON_DEATH
# 139 - SKELETON_HURT
# 140 - SKELETON_IDLE
# 141 - SKELETON_WALK
# 142 - SLIME_ATTACK
# 143 - SLIME_WALK
# 144 - SLIME_WALK2
# 145 - SPIDER_DEATH
# 146 - SPIDER_IDLE
# 147 - SPIDER_WALK
# 148 - SPLASH
# 149 - SPLASH2
# 150 - STEP_GRASS
# 151 - STEP_GRAVEL
# 152 - STEP_LADDER
# 153 - STEP_SAND
# 154 - STEP_SNOW
# 155 - STEP_STONE
# 156 - STEP_WOOD
# 157 - STEP_WOOL
# 158 - SUCCESSFUL_HIT
# 159 - SWIM
# 160 - VILLAGER_DEATH
# 161 - VILLAGER_HAGGLE
# 162 - VILLAGER_HIT
# 163 - VILLAGER_IDLE
# 164 - VILLAGER_NO
# 165 - VILLAGER_YES
# 166 - WATER
# 167 - WITHER_DEATH
# 168 - WITHER_HURT
# 169 - WITHER_IDLE
# 170 - WITHER_SHOOT
# 171 - WITHER_SPAWN
# 172 - WOLF_BARK
# 173 - WOLF_DEATH
# 174 - WOLF_GROWL
# 175 - WOLF_HOWL
# 176 - WOLF_HURT
# 177 - WOLF_PANT
# 178 - WOLF_SHAKE
# 179 - WOLF_WALK
# 180 - WOLF_WHINE
# 181 - WOOD_CLICK
# 182 - ZOMBIE_DEATH
# 183 - ZOMBIE_HURT
# 184 - ZOMBIE_IDLE
# 185 - ZOMBIE_INFECT
# 186 - ZOMBIE_METAL
# 187 - ZOMBIE_PIG_ANGRY
# 188 - ZOMBIE_PIG_DEATH
# 189 - ZOMBIE_PIG_HURT
# 190 - ZOMBIE_PIG_IDLE
# 191 - ZOMBIE_REMEDY
# 192 - ZOMBIE_UNFECT
# 193 - ZOMBIE_WALK
# 194 - ZOMBIE_WOOD
# 195 - ZOMBIE_WOODBREAK
