# Configuration file for MessageTones 1.10
# https://www.spigotmc.org/resources/messagetones.30529/
# Created by KevinNovak

# ============================================
# Help
# ============================================
# Sound
#  - The ID of the sound to play.
#  - See the "Sound IDS" section for a list of IDs.
# Pitch
#  - The pitch to play the sound at.
#  - For example 1.0 is the normal sound pitch.
#  - 0.5 would create a lower pitch.
#  - 2.0 would create a higher pitch.
# Volume
#  - The volume to play the sound at.
#  - For example 1.0 is the normal sound volume.
#  - 0.5 would create a quieter sound.
#  - 2.0 would create a louder sound.

# ============================================
# Metrics
# ============================================
# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/MessageTones/
# default: metrics: true
metrics: true

# ============================================
# Private Messages
# ============================================
# Whether private messages should play sounds to players.
# default: msgEnabled: true
msgEnabled: true

# Should private messages sounds should be "On" for new players?
# default: msgDefaultOn: true
msgDefaultOn: true

# Recommended Sounds: 264 (ENTITY_ITEM_PICKUP), 73 (BLOCK_NOTE_PLING), 295 (ENTITY_PLAYER_BURP)
# default: msgSound: 264
msgSound: 264

# default: msgPitch: 1.0
msgPitch: 1.0

# default: msgVolume: 0.8
msgVolume: 0.8

# The message text that triggers a sound.
# Should uniquely identify private messages.
# For example, in Essentials/EssentialsX every message contains " -> me]".
# default: msgTrigger: ' -> me]'
msgTrigger: ' -> me]'

# ============================================
# Broadcast
# ============================================
# Whether broadcasted messages should play sounds to players.
# Broadcaster must have the messagetones.broadcast permission.
# default: broadcastEnabled: true
broadcastEnabled: true

# Should broadcast sounds be "On" for new players?
# default: msgDefaultOn: true
broadcastDefaultOn: true

# Recommended Sounds: 200 (ENTITY_FIREWORK_LARGE_BLAST), 268 (ENTITY_LIGHTNING_THUNDER)
# default: broadcastSound: 200
broadcastSound: 200

# default: broadcastPitch: 1.0
broadcastPitch: 1.0

# default: broadcastVolume: 1.0
broadcastVolume: 1.0

# The broadcast command that triggers a sound.
# default: broadcastCommand: 'broadcast'
broadcastCommand: 'broadcast'

# ============================================
# Player Joins
# ============================================
# Whether to play a sound when normal players join.
# default: joinPlayerEnabled: false
joinPlayerEnabled: true

# Should player join sounds should be "On" for new players?
# default: joinPlayerDefaultOn: true
joinPlayerDefaultOn: true

# Recommended Sounds: 112 (BLOCK_WOODEN_DOOR_OPEN)
# default: joinPlayerSound: 112
joinPlayerSound: 112

# default: joinPlayerPitch: 1.0
joinPlayerPitch: 1.0

# default: joinPlayerVolume: 0.5
joinPlayerVolume: 0.5

# ============================================
# Admin Joins
# ============================================
# Whether to play a sound when an admin joins.
# Admin must have the messagetones.admin permission.
# default: joinAdminEnabled: false
joinAdminEnabled: true

# Should admin join sounds should be "On" for new players?
# default: joinAdminDefaultOn: true
joinAdminDefaultOn: true

# Recommended Sounds: 204 (ENTITY_FIREWORK_TWINKLE)
# default: joinAdminSound: 204
joinAdminSound: 204

# default: joinAdminPitch: 1.0
joinAdminPitch: 1.0

# default: joinAdminVolume: 0.5
joinAdminVolume: 0.5

# ============================================
# Owner Joins
# ============================================
# Whether to play a sound when an owner joins.
# Owner must have the messagetones.owner permission.
# default: joinOwnerEnabled: false
joinOwnerEnabled: true

# Should owner join sounds should be "On" for new players?
# default: joinOwnerDefaultOn: true
joinOwnerDefaultOn: true

# Recommended Sounds: 298 (ENTITY_PLAYER_LEVELUP)
# default: joinOwnerSound: 298
joinOwnerSound: 298

# default: joinOwnerPitch: 1.0
joinOwnerPitch: 1.0

# default: joinOwnerVolume: 0.5
joinOwnerVolume: 0.5

# ============================================
# Hotbar
# ============================================
# Whether to play a sound when players switch items in the hotbar.
# default: hotbarEnabled: false
hotbarEnabled: false

# Should hotbar sounds should be "On" for new players?
# default: hotbarDefaultOn: true
hotbarDefaultOn: true

# Recommended Sounds: 264 (ENTITY_ITEM_PICKUP)
# default: hotbarSound: 264
hotbarSound: 264

# default: hotbarPitch: 0.5
hotbarPitch: 0.5

# default: hotbarVolume: 0.2
hotbarVolume: 0.2

# ============================================
# Language
# ============================================
noconsole: '&cConsole cannot run MessageTones commands!'
notpermitted: '&cYou are not permitted to do this!'
testmessage: '&7Played test message sound.'
testbroadcast: '&7Played test broadcast sound.'
testownerjoin: '&7Played test owner join sound.'
testadminjoin: '&7Played test admin join sound.'
testplayerjoin: '&7Played test player join sound.'
testhotbar: '&7Played test hotbar sound.'
help:
- '&e---------- &6MessageTones &e----------'
- '&b/mt message &7- Test message sound.'
- '&b/mt broadcast &7- Test broadcast sound.'
- '&b/mt ownerjoin &7- Test owner join sound.'
- '&b/mt adminjoin &7- Test admin join sound.'
- '&b/mt playerjoin &7- Test player join sound.'
- '&b/mt hotbar &7- Test hotbar sound.'

# ============================================
# Minecraft 1.10 - Sound IDs
# ============================================
# 1 - AMBIENT_CAVE
# 2 - BLOCK_ANVIL_BREAK
# 3 - BLOCK_ANVIL_DESTROY
# 4 - BLOCK_ANVIL_FALL
# 5 - BLOCK_ANVIL_HIT
# 6 - BLOCK_ANVIL_LAND
# 7 - BLOCK_ANVIL_PLACE
# 8 - BLOCK_ANVIL_STEP
# 9 - BLOCK_ANVIL_USE
# 10 - BLOCK_BREWING_STAND_BREW
# 11 - BLOCK_CHEST_CLOSE
# 12 - BLOCK_CHEST_LOCKED
# 13 - BLOCK_CHEST_OPEN
# 14 - BLOCK_CHORUS_FLOWER_DEATH
# 15 - BLOCK_CHORUS_FLOWER_GROW
# 16 - BLOCK_CLOTH_BREAK
# 17 - BLOCK_CLOTH_FALL
# 18 - BLOCK_CLOTH_HIT
# 19 - BLOCK_CLOTH_PLACE
# 20 - BLOCK_CLOTH_STEP
# 21 - BLOCK_COMPARATOR_CLICK
# 22 - BLOCK_DISPENSER_DISPENSE
# 23 - BLOCK_DISPENSER_FAIL
# 24 - BLOCK_DISPENSER_LAUNCH
# 25 - BLOCK_ENCHANTMENT_TABLE_USE
# 26 - BLOCK_ENDERCHEST_CLOSE
# 27 - BLOCK_ENDERCHEST_OPEN
# 28 - BLOCK_END_GATEWAY_SPAWN
# 29 - BLOCK_FENCE_GATE_CLOSE
# 30 - BLOCK_FENCE_GATE_OPEN
# 31 - BLOCK_FIRE_AMBIENT
# 32 - BLOCK_FIRE_EXTINGUISH
# 33 - BLOCK_FURNACE_FIRE_CRACKLE
# 34 - BLOCK_GLASS_BREAK
# 35 - BLOCK_GLASS_FALL
# 36 - BLOCK_GLASS_HIT
# 37 - BLOCK_GLASS_PLACE
# 38 - BLOCK_GLASS_STEP
# 39 - BLOCK_GRASS_BREAK
# 40 - BLOCK_GRASS_FALL
# 41 - BLOCK_GRASS_HIT
# 42 - BLOCK_GRASS_PLACE
# 43 - BLOCK_GRASS_STEP
# 44 - BLOCK_GRAVEL_BREAK
# 45 - BLOCK_GRAVEL_FALL
# 46 - BLOCK_GRAVEL_HIT
# 47 - BLOCK_GRAVEL_PLACE
# 48 - BLOCK_GRAVEL_STEP
# 49 - BLOCK_IRON_DOOR_CLOSE
# 50 - BLOCK_IRON_DOOR_OPEN
# 51 - BLOCK_IRON_TRAPDOOR_CLOSE
# 52 - BLOCK_IRON_TRAPDOOR_OPEN
# 53 - BLOCK_LADDER_BREAK
# 54 - BLOCK_LADDER_FALL
# 55 - BLOCK_LADDER_HIT
# 56 - BLOCK_LADDER_PLACE
# 57 - BLOCK_LADDER_STEP
# 58 - BLOCK_LAVA_AMBIENT
# 59 - BLOCK_LAVA_EXTINGUISH
# 60 - BLOCK_LAVA_POP
# 61 - BLOCK_LEVER_CLICK
# 62 - BLOCK_METAL_BREAK
# 63 - BLOCK_METAL_FALL
# 64 - BLOCK_METAL_HIT
# 65 - BLOCK_METAL_PLACE
# 66 - BLOCK_METAL_PRESSUREPLATE_CLICK_OFF
# 67 - BLOCK_METAL_PRESSUREPLATE_CLICK_ON
# 68 - BLOCK_METAL_STEP
# 69 - BLOCK_NOTE_BASEDRUM
# 70 - BLOCK_NOTE_BASS
# 71 - BLOCK_NOTE_HARP
# 72 - BLOCK_NOTE_HAT
# 73 - BLOCK_NOTE_PLING
# 74 - BLOCK_NOTE_SNARE
# 75 - BLOCK_PISTON_CONTRACT
# 76 - BLOCK_PISTON_EXTEND
# 77 - BLOCK_PORTAL_AMBIENT
# 78 - BLOCK_PORTAL_TRAVEL
# 79 - BLOCK_PORTAL_TRIGGER
# 80 - BLOCK_REDSTONE_TORCH_BURNOUT
# 81 - BLOCK_SAND_BREAK
# 82 - BLOCK_SAND_FALL
# 83 - BLOCK_SAND_HIT
# 84 - BLOCK_SAND_PLACE
# 85 - BLOCK_SAND_STEP
# 86 - BLOCK_SLIME_BREAK
# 87 - BLOCK_SLIME_FALL
# 88 - BLOCK_SLIME_HIT
# 89 - BLOCK_SLIME_PLACE
# 90 - BLOCK_SLIME_STEP
# 91 - BLOCK_SNOW_BREAK
# 92 - BLOCK_SNOW_FALL
# 93 - BLOCK_SNOW_HIT
# 94 - BLOCK_SNOW_PLACE
# 95 - BLOCK_SNOW_STEP
# 96 - BLOCK_STONE_BREAK
# 97 - BLOCK_STONE_BUTTON_CLICK_OFF
# 98 - BLOCK_STONE_BUTTON_CLICK_ON
# 99 - BLOCK_STONE_FALL
# 100 - BLOCK_STONE_HIT
# 101 - BLOCK_STONE_PLACE
# 102 - BLOCK_STONE_PRESSUREPLATE_CLICK_OFF
# 103 - BLOCK_STONE_PRESSUREPLATE_CLICK_ON
# 104 - BLOCK_STONE_STEP
# 105 - BLOCK_TRIPWIRE_ATTACH
# 106 - BLOCK_TRIPWIRE_CLICK_OFF
# 107 - BLOCK_TRIPWIRE_CLICK_ON
# 108 - BLOCK_TRIPWIRE_DETACH
# 109 - BLOCK_WATERLILY_PLACE
# 110 - BLOCK_WATER_AMBIENT
# 111 - BLOCK_WOODEN_DOOR_CLOSE
# 112 - BLOCK_WOODEN_DOOR_OPEN
# 113 - BLOCK_WOODEN_TRAPDOOR_CLOSE
# 114 - BLOCK_WOODEN_TRAPDOOR_OPEN
# 115 - BLOCK_WOOD_BREAK
# 116 - BLOCK_WOOD_BUTTON_CLICK_OFF
# 117 - BLOCK_WOOD_BUTTON_CLICK_ON
# 118 - BLOCK_WOOD_FALL
# 119 - BLOCK_WOOD_HIT
# 120 - BLOCK_WOOD_PLACE
# 121 - BLOCK_WOOD_PRESSUREPLATE_CLICK_OFF
# 122 - BLOCK_WOOD_PRESSUREPLATE_CLICK_ON
# 123 - BLOCK_WOOD_STEP
# 124 - ENCHANT_THORNS_HIT
# 125 - ENTITY_ARMORSTAND_BREAK
# 126 - ENTITY_ARMORSTAND_FALL
# 127 - ENTITY_ARMORSTAND_HIT
# 128 - ENTITY_ARMORSTAND_PLACE
# 129 - ENTITY_ARROW_HIT
# 130 - ENTITY_ARROW_HIT_PLAYER
# 131 - ENTITY_ARROW_SHOOT
# 132 - ENTITY_BAT_AMBIENT
# 133 - ENTITY_BAT_DEATH
# 134 - ENTITY_BAT_HURT
# 135 - ENTITY_BAT_LOOP
# 136 - ENTITY_BAT_TAKEOFF
# 137 - ENTITY_BLAZE_AMBIENT
# 138 - ENTITY_BLAZE_BURN
# 139 - ENTITY_BLAZE_DEATH
# 140 - ENTITY_BLAZE_HURT
# 141 - ENTITY_BLAZE_SHOOT
# 142 - ENTITY_BOBBER_SPLASH
# 143 - ENTITY_BOBBER_THROW
# 144 - ENTITY_CAT_AMBIENT
# 145 - ENTITY_CAT_DEATH
# 146 - ENTITY_CAT_HISS
# 147 - ENTITY_CAT_HURT
# 148 - ENTITY_CAT_PURR
# 149 - ENTITY_CAT_PURREOW
# 150 - ENTITY_CHICKEN_AMBIENT
# 151 - ENTITY_CHICKEN_DEATH
# 152 - ENTITY_CHICKEN_EGG
# 153 - ENTITY_CHICKEN_HURT
# 154 - ENTITY_CHICKEN_STEP
# 155 - ENTITY_COW_AMBIENT
# 156 - ENTITY_COW_DEATH
# 157 - ENTITY_COW_HURT
# 158 - ENTITY_COW_MILK
# 159 - ENTITY_COW_STEP
# 160 - ENTITY_CREEPER_DEATH
# 161 - ENTITY_CREEPER_HURT
# 162 - ENTITY_CREEPER_PRIMED
# 163 - ENTITY_DONKEY_AMBIENT
# 164 - ENTITY_DONKEY_ANGRY
# 165 - ENTITY_DONKEY_CHEST
# 166 - ENTITY_DONKEY_DEATH
# 167 - ENTITY_DONKEY_HURT
# 168 - ENTITY_EGG_THROW
# 169 - ENTITY_ELDER_GUARDIAN_AMBIENT
# 170 - ENTITY_ELDER_GUARDIAN_AMBIENT_LAND
# 171 - ENTITY_ELDER_GUARDIAN_CURSE
# 172 - ENTITY_ELDER_GUARDIAN_DEATH
# 173 - ENTITY_ELDER_GUARDIAN_DEATH_LAND
# 174 - ENTITY_ELDER_GUARDIAN_HURT
# 175 - ENTITY_ELDER_GUARDIAN_HURT_LAND
# 176 - ENTITY_ENDERDRAGON_AMBIENT
# 177 - ENTITY_ENDERDRAGON_DEATH
# 178 - ENTITY_ENDERDRAGON_FIREBALL_EXPLODE
# 179 - ENTITY_ENDERDRAGON_FLAP
# 180 - ENTITY_ENDERDRAGON_GROWL
# 181 - ENTITY_ENDERDRAGON_HURT
# 182 - ENTITY_ENDERDRAGON_SHOOT
# 183 - ENTITY_ENDEREYE_LAUNCH
# 184 - ENTITY_ENDERMEN_AMBIENT
# 185 - ENTITY_ENDERMEN_DEATH
# 186 - ENTITY_ENDERMEN_HURT
# 187 - ENTITY_ENDERMEN_SCREAM
# 188 - ENTITY_ENDERMEN_STARE
# 189 - ENTITY_ENDERMEN_TELEPORT
# 190 - ENTITY_ENDERMITE_AMBIENT
# 191 - ENTITY_ENDERMITE_DEATH
# 192 - ENTITY_ENDERMITE_HURT
# 193 - ENTITY_ENDERMITE_STEP
# 194 - ENTITY_ENDERPEARL_THROW
# 195 - ENTITY_EXPERIENCE_BOTTLE_THROW
# 196 - ENTITY_EXPERIENCE_ORB_PICKUP
# 197 - ENTITY_EXPERIENCE_ORB_TOUCH
# 198 - ENTITY_FIREWORK_BLAST
# 199 - ENTITY_FIREWORK_BLAST_FAR
# 200 - ENTITY_FIREWORK_LARGE_BLAST
# 201 - ENTITY_FIREWORK_LARGE_BLAST_FAR
# 202 - ENTITY_FIREWORK_LAUNCH
# 203 - ENTITY_FIREWORK_SHOOT
# 204 - ENTITY_FIREWORK_TWINKLE
# 205 - ENTITY_FIREWORK_TWINKLE_FAR
# 206 - ENTITY_GENERIC_BIG_FALL
# 207 - ENTITY_GENERIC_BURN
# 208 - ENTITY_GENERIC_DEATH
# 209 - ENTITY_GENERIC_DRINK
# 210 - ENTITY_GENERIC_EAT
# 211 - ENTITY_GENERIC_EXPLODE
# 212 - ENTITY_GENERIC_EXTINGUISH_FIRE
# 213 - ENTITY_GENERIC_HURT
# 214 - ENTITY_GENERIC_SMALL_FALL
# 215 - ENTITY_GENERIC_SPLASH
# 216 - ENTITY_GENERIC_SWIM
# 217 - ENTITY_GHAST_AMBIENT
# 218 - ENTITY_GHAST_DEATH
# 219 - ENTITY_GHAST_HURT
# 220 - ENTITY_GHAST_SCREAM
# 221 - ENTITY_GHAST_SHOOT
# 222 - ENTITY_GHAST_WARN
# 223 - ENTITY_GUARDIAN_AMBIENT
# 224 - ENTITY_GUARDIAN_AMBIENT_LAND
# 225 - ENTITY_GUARDIAN_ATTACK
# 226 - ENTITY_GUARDIAN_DEATH
# 227 - ENTITY_GUARDIAN_DEATH_LAND
# 228 - ENTITY_GUARDIAN_FLOP
# 229 - ENTITY_GUARDIAN_HURT
# 230 - ENTITY_GUARDIAN_HURT_LAND
# 231 - ENTITY_HORSE_AMBIENT
# 232 - ENTITY_HORSE_ANGRY
# 233 - ENTITY_HORSE_ARMOR
# 234 - ENTITY_HORSE_BREATHE
# 235 - ENTITY_HORSE_DEATH
# 236 - ENTITY_HORSE_EAT
# 237 - ENTITY_HORSE_GALLOP
# 238 - ENTITY_HORSE_HURT
# 239 - ENTITY_HORSE_JUMP
# 240 - ENTITY_HORSE_LAND
# 241 - ENTITY_HORSE_SADDLE
# 242 - ENTITY_HORSE_STEP
# 243 - ENTITY_HORSE_STEP_WOOD
# 244 - ENTITY_HOSTILE_BIG_FALL
# 245 - ENTITY_HOSTILE_DEATH
# 246 - ENTITY_HOSTILE_HURT
# 247 - ENTITY_HOSTILE_SMALL_FALL
# 248 - ENTITY_HOSTILE_SPLASH
# 249 - ENTITY_HOSTILE_SWIM
# 250 - ENTITY_HUSK_AMBIENT
# 251 - ENTITY_HUSK_DEATH
# 252 - ENTITY_HUSK_HURT
# 253 - ENTITY_HUSK_STEP
# 254 - ENTITY_IRONGOLEM_ATTACK
# 255 - ENTITY_IRONGOLEM_DEATH
# 256 - ENTITY_IRONGOLEM_HURT
# 257 - ENTITY_IRONGOLEM_STEP
# 258 - ENTITY_ITEMFRAME_ADD_ITEM
# 259 - ENTITY_ITEMFRAME_BREAK
# 260 - ENTITY_ITEMFRAME_PLACE
# 261 - ENTITY_ITEMFRAME_REMOVE_ITEM
# 262 - ENTITY_ITEMFRAME_ROTATE_ITEM
# 263 - ENTITY_ITEM_BREAK
# 264 - ENTITY_ITEM_PICKUP
# 265 - ENTITY_LEASHKNOT_BREAK
# 266 - ENTITY_LEASHKNOT_PLACE
# 267 - ENTITY_LIGHTNING_IMPACT
# 268 - ENTITY_LIGHTNING_THUNDER
# 269 - ENTITY_LINGERINGPOTION_THROW
# 270 - ENTITY_MAGMACUBE_DEATH
# 271 - ENTITY_MAGMACUBE_HURT
# 272 - ENTITY_MAGMACUBE_JUMP
# 273 - ENTITY_MAGMACUBE_SQUISH
# 274 - ENTITY_MINECART_INSIDE
# 275 - ENTITY_MINECART_RIDING
# 276 - ENTITY_MOOSHROOM_SHEAR
# 277 - ENTITY_MULE_AMBIENT
# 278 - ENTITY_MULE_DEATH
# 279 - ENTITY_MULE_HURT
# 280 - ENTITY_PAINTING_BREAK
# 281 - ENTITY_PAINTING_PLACE
# 282 - ENTITY_PIG_AMBIENT
# 283 - ENTITY_PIG_DEATH
# 284 - ENTITY_PIG_HURT
# 285 - ENTITY_PIG_SADDLE
# 286 - ENTITY_PIG_STEP
# 287 - ENTITY_PLAYER_ATTACK_CRIT
# 288 - ENTITY_PLAYER_ATTACK_KNOCKBACK
# 289 - ENTITY_PLAYER_ATTACK_NODAMAGE
# 290 - ENTITY_PLAYER_ATTACK_STRONG
# 291 - ENTITY_PLAYER_ATTACK_SWEEP
# 292 - ENTITY_PLAYER_ATTACK_WEAK
# 293 - ENTITY_PLAYER_BIG_FALL
# 294 - ENTITY_PLAYER_BREATH
# 295 - ENTITY_PLAYER_BURP
# 296 - ENTITY_PLAYER_DEATH
# 297 - ENTITY_PLAYER_HURT
# 298 - ENTITY_PLAYER_LEVELUP
# 299 - ENTITY_PLAYER_SMALL_FALL
# 300 - ENTITY_PLAYER_SPLASH
# 301 - ENTITY_PLAYER_SWIM
# 302 - ENTITY_POLAR_BEAR_AMBIENT
# 303 - ENTITY_POLAR_BEAR_BABY_AMBIENT
# 304 - ENTITY_POLAR_BEAR_DEATH
# 305 - ENTITY_POLAR_BEAR_HURT
# 306 - ENTITY_POLAR_BEAR_STEP
# 307 - ENTITY_POLAR_BEAR_WARNING
# 308 - ENTITY_RABBIT_AMBIENT
# 309 - ENTITY_RABBIT_ATTACK
# 310 - ENTITY_RABBIT_DEATH
# 311 - ENTITY_RABBIT_HURT
# 312 - ENTITY_RABBIT_JUMP
# 313 - ENTITY_SHEEP_AMBIENT
# 314 - ENTITY_SHEEP_DEATH
# 315 - ENTITY_SHEEP_HURT
# 316 - ENTITY_SHEEP_SHEAR
# 317 - ENTITY_SHEEP_STEP
# 318 - ENTITY_SHULKER_AMBIENT
# 319 - ENTITY_SHULKER_BULLET_HIT
# 320 - ENTITY_SHULKER_BULLET_HURT
# 321 - ENTITY_SHULKER_CLOSE
# 322 - ENTITY_SHULKER_DEATH
# 323 - ENTITY_SHULKER_HURT
# 324 - ENTITY_SHULKER_HURT_CLOSED
# 325 - ENTITY_SHULKER_OPEN
# 326 - ENTITY_SHULKER_SHOOT
# 327 - ENTITY_SHULKER_TELEPORT
# 328 - ENTITY_SILVERFISH_AMBIENT
# 329 - ENTITY_SILVERFISH_DEATH
# 330 - ENTITY_SILVERFISH_HURT
# 331 - ENTITY_SILVERFISH_STEP
# 332 - ENTITY_SKELETON_AMBIENT
# 333 - ENTITY_SKELETON_DEATH
# 334 - ENTITY_SKELETON_HORSE_AMBIENT
# 335 - ENTITY_SKELETON_HORSE_DEATH
# 336 - ENTITY_SKELETON_HORSE_HURT
# 337 - ENTITY_SKELETON_HURT
# 338 - ENTITY_SKELETON_SHOOT
# 339 - ENTITY_SKELETON_STEP
# 340 - ENTITY_SLIME_ATTACK
# 341 - ENTITY_SLIME_DEATH
# 342 - ENTITY_SLIME_HURT
# 343 - ENTITY_SLIME_JUMP
# 344 - ENTITY_SLIME_SQUISH
# 345 - ENTITY_SMALL_MAGMACUBE_DEATH
# 346 - ENTITY_SMALL_MAGMACUBE_HURT
# 347 - ENTITY_SMALL_MAGMACUBE_SQUISH
# 348 - ENTITY_SMALL_SLIME_DEATH
# 349 - ENTITY_SMALL_SLIME_HURT
# 350 - ENTITY_SMALL_SLIME_JUMP
# 351 - ENTITY_SMALL_SLIME_SQUISH
# 352 - ENTITY_SNOWBALL_THROW
# 353 - ENTITY_SNOWMAN_AMBIENT
# 354 - ENTITY_SNOWMAN_DEATH
# 355 - ENTITY_SNOWMAN_HURT
# 356 - ENTITY_SNOWMAN_SHOOT
# 357 - ENTITY_SPIDER_AMBIENT
# 358 - ENTITY_SPIDER_DEATH
# 359 - ENTITY_SPIDER_HURT
# 360 - ENTITY_SPIDER_STEP
# 361 - ENTITY_SPLASH_POTION_BREAK
# 362 - ENTITY_SPLASH_POTION_THROW
# 363 - ENTITY_SQUID_AMBIENT
# 364 - ENTITY_SQUID_DEATH
# 365 - ENTITY_SQUID_HURT
# 366 - ENTITY_STRAY_AMBIENT
# 367 - ENTITY_STRAY_DEATH
# 368 - ENTITY_STRAY_HURT
# 369 - ENTITY_STRAY_STEP
# 370 - ENTITY_TNT_PRIMED
# 371 - ENTITY_VILLAGER_AMBIENT
# 372 - ENTITY_VILLAGER_DEATH
# 373 - ENTITY_VILLAGER_HURT
# 374 - ENTITY_VILLAGER_NO
# 375 - ENTITY_VILLAGER_TRADING
# 376 - ENTITY_VILLAGER_YES
# 377 - ENTITY_WITCH_AMBIENT
# 378 - ENTITY_WITCH_DEATH
# 379 - ENTITY_WITCH_DRINK
# 380 - ENTITY_WITCH_HURT
# 381 - ENTITY_WITCH_THROW
# 382 - ENTITY_WITHER_AMBIENT
# 383 - ENTITY_WITHER_BREAK_BLOCK
# 384 - ENTITY_WITHER_DEATH
# 385 - ENTITY_WITHER_HURT
# 386 - ENTITY_WITHER_SHOOT
# 387 - ENTITY_WITHER_SKELETON_AMBIENT
# 388 - ENTITY_WITHER_SKELETON_DEATH
# 389 - ENTITY_WITHER_SKELETON_HURT
# 390 - ENTITY_WITHER_SKELETON_STEP
# 391 - ENTITY_WITHER_SPAWN
# 392 - ENTITY_WOLF_AMBIENT
# 393 - ENTITY_WOLF_DEATH
# 394 - ENTITY_WOLF_GROWL
# 395 - ENTITY_WOLF_HOWL
# 396 - ENTITY_WOLF_HURT
# 397 - ENTITY_WOLF_PANT
# 398 - ENTITY_WOLF_SHAKE
# 399 - ENTITY_WOLF_STEP
# 400 - ENTITY_WOLF_WHINE
# 401 - ENTITY_ZOMBIE_AMBIENT
# 402 - ENTITY_ZOMBIE_ATTACK_DOOR_WOOD
# 403 - ENTITY_ZOMBIE_ATTACK_IRON_DOOR
# 404 - ENTITY_ZOMBIE_BREAK_DOOR_WOOD
# 405 - ENTITY_ZOMBIE_DEATH
# 406 - ENTITY_ZOMBIE_HORSE_AMBIENT
# 407 - ENTITY_ZOMBIE_HORSE_DEATH
# 408 - ENTITY_ZOMBIE_HORSE_HURT
# 409 - ENTITY_ZOMBIE_HURT
# 410 - ENTITY_ZOMBIE_INFECT
# 411 - ENTITY_ZOMBIE_PIG_AMBIENT
# 412 - ENTITY_ZOMBIE_PIG_ANGRY
# 413 - ENTITY_ZOMBIE_PIG_DEATH
# 414 - ENTITY_ZOMBIE_PIG_HURT
# 415 - ENTITY_ZOMBIE_STEP
# 416 - ENTITY_ZOMBIE_VILLAGER_AMBIENT
# 417 - ENTITY_ZOMBIE_VILLAGER_CONVERTED
# 418 - ENTITY_ZOMBIE_VILLAGER_CURE
# 419 - ENTITY_ZOMBIE_VILLAGER_DEATH
# 420 - ENTITY_ZOMBIE_VILLAGER_HURT
# 421 - ENTITY_ZOMBIE_VILLAGER_STEP
# 422 - ITEM_ARMOR_EQUIP_CHAIN
# 423 - ITEM_ARMOR_EQUIP_DIAMOND
# 424 - ITEM_ARMOR_EQUIP_GENERIC
# 425 - ITEM_ARMOR_EQUIP_GOLD
# 426 - ITEM_ARMOR_EQUIP_IRON
# 427 - ITEM_ARMOR_EQUIP_LEATHER
# 428 - ITEM_BOTTLE_FILL
# 429 - ITEM_BOTTLE_FILL_DRAGONBREATH
# 430 - ITEM_BUCKET_EMPTY
# 431 - ITEM_BUCKET_EMPTY_LAVA
# 432 - ITEM_BUCKET_FILL
# 433 - ITEM_BUCKET_FILL_LAVA
# 434 - ITEM_CHORUS_FRUIT_TELEPORT
# 435 - ITEM_ELYTRA_FLYING
# 436 - ITEM_FIRECHARGE_USE
# 437 - ITEM_FLINTANDSTEEL_USE
# 438 - ITEM_HOE_TILL
# 439 - ITEM_SHIELD_BLOCK
# 440 - ITEM_SHIELD_BREAK
# 441 - ITEM_SHOVEL_FLATTEN
# 442 - MUSIC_CREATIVE
# 443 - MUSIC_CREDITS
# 444 - MUSIC_DRAGON
# 445 - MUSIC_END
# 446 - MUSIC_GAME
# 447 - MUSIC_MENU
# 448 - MUSIC_NETHER
# 449 - RECORD_11 -
# 450 - RECORD_13 -
# 451 - RECORD_BLOCKS
# 452 - RECORD_CAT
# 453 - RECORD_CHIRP
# 454 - RECORD_FAR
# 455 - RECORD_MALL
# 456 - RECORD_MELLOHI
# 457 - RECORD_STAL
# 458 - RECORD_STRAD
# 459 - RECORD_WAIT
# 460 - RECORD_WARD
# 461 - UI_BUTTON_CLICK
# 462 - WEATHER_RAIN
# 463 - WEATHER_RAIN_ABOVE

# Do not touch:
copied: true
