# Configuration file for MessageTones

# Recommended Sounds: 16, 104, 117
# default: msgSound: 104
msgSound: 104

# Language
noconsole: '&cConsole cannot run MessageTones commands!'

# Whether or not to collect data on plugin usage
# Viewable at http://mcstats.org/plugin/MessageTones
# default: metrics: true
metrics: true