name: MessageTones
version: 1.1.1
main: me.kevinnovak.messagetones.MessageTones
author: KevinNovak
description: Allows messages to have tones!
depend: [ProtocolLib]

commands:
    mt:
        usage: /<command>
        description: Lists MessageTones commands.
        aliases: [messagetones, messagetone, tone]
        
permissions:
    messagetones.broadcast:
        description: Plays sound on /broadcast.
        default: op
    messagetones.admin:
        description: Plays admin login sound.
        default: false
    messagetones.owner:
        description: Plays owner login sound.
        default: false